name: CI (Test And Build)

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  tester:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: List files
      run: ls -lah

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tester.py

  build:
    runs-on: ubuntu-latest
    needs: tester

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build And Push Docker image on Docker Hub
      run: |
        docker build -t mustafa3li/palestine:latest .
        docker push mustafa3li/palestine:latest